/*
 * #%L
 * GWT Bootstrap Modern
 * %%
 * Copyright (C) 2026 Carl Stainton
 * %%
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * #L%
 */
package org.gwtbootstrap3.teavm.demo;

import com.google.gwt.core.client.EntryPoint;
import com.google.gwt.user.client.ui.RootPanel;
import org.gwtbootstrap3.client.ui.Alert;
import org.gwtbootstrap3.client.ui.Anchor;
import org.gwtbootstrap3.client.ui.Badge;
import org.gwtbootstrap3.client.ui.Button;
import org.gwtbootstrap3.client.ui.Column;
import org.gwtbootstrap3.client.ui.Container;
import org.gwtbootstrap3.client.ui.Description;
import org.gwtbootstrap3.client.ui.DescriptionData;
import org.gwtbootstrap3.client.ui.DescriptionTitle;
import org.gwtbootstrap3.client.ui.Heading;
import org.gwtbootstrap3.client.ui.Label;
import org.gwtbootstrap3.client.ui.Lead;
import org.gwtbootstrap3.client.ui.ListGroup;
import org.gwtbootstrap3.client.ui.ListGroupItem;
import org.gwtbootstrap3.client.ui.Panel;
import org.gwtbootstrap3.client.ui.PanelBody;
import org.gwtbootstrap3.client.ui.PanelFooter;
import org.gwtbootstrap3.client.ui.PanelHeader;
import org.gwtbootstrap3.client.ui.PageHeader;
import org.gwtbootstrap3.client.ui.Row;
import org.gwtbootstrap3.client.ui.Well;
import org.gwtbootstrap3.client.ui.constants.AlertType;
import org.gwtbootstrap3.client.ui.constants.ButtonType;
import org.gwtbootstrap3.client.ui.constants.ColumnSize;
import org.gwtbootstrap3.client.ui.constants.HeadingSize;
import org.gwtbootstrap3.client.ui.constants.ListGroupItemType;
import org.gwtbootstrap3.client.ui.constants.PanelType;
import org.gwtbootstrap3.client.ui.html.Paragraph;
import org.gwtbootstrap3.client.ui.html.Text;

public final class GwtCompatSmokeApp implements EntryPoint {
    public static void main(final String[] args) {
        new GwtCompatSmokeApp().onModuleLoad();
    }

    @Override
    public void onModuleLoad() {
        final Container container = new Container();
        container.add(new PageHeader("TeaVM Bootstrap 3 Modern"));
        container.add(new Lead("This page is rendered with GWT-style widget APIs running on TeaVM."));
        container.add(new Alert("Same package names, TeaVM DOM backend.", AlertType.INFO));

        final Row row = new Row();
        row.add(new Column(ColumnSize.MD_6, new Button("Primary action", event -> {
            final Label label = new Label("clicked");
            container.add(label);
        })));
        row.add(new Column(ColumnSize.MD_6, new Anchor("GWT Bootstrap Modern", "https://github.com/cstainton/gwtbootstrap-modern")));
        container.add(row);

        final Panel panel = new Panel(PanelType.PRIMARY);
        panel.add(new PanelHeader("Compile checked widgets"));
        final PanelBody panelBody = new PanelBody();
        panelBody.add(new Heading(HeadingSize.H3, "Current TeaVM subset"));
        panelBody.add(new Paragraph("Panels, alerts, lists, labels, badges, descriptions, wells and simple HTML wrappers."));
        final ListGroup group = new ListGroup();
        final ListGroupItem item = new ListGroupItem("Bootstrap 3 class mapping");
        item.setType(ListGroupItemType.SUCCESS);
        group.add(item);
        group.add(new ListGroupItem("GWT-style RootPanel and click handlers"));
        panelBody.add(group);
        panel.add(panelBody);
        final PanelFooter footer = new PanelFooter();
        footer.add(new Text("Smoke page generated by TeaVM."));
        panel.add(footer);
        container.add(panel);

        final Description description = new Description();
        description.add(new DescriptionTitle("Artifact"));
        description.add(new DescriptionData("teavm-bootstrap3-modern"));
        description.add(new DescriptionTitle("Runtime"));
        description.add(new DescriptionData("gwt-teavm-compat"));
        container.add(description);

        container.add(new Well());
        container.add(new Badge("Bootstrap badge"));

        final Button button = new Button("Secondary action");
        button.setType(ButtonType.PRIMARY);
        container.add(button);

        RootPanel.get().add(container);
    }
}
