// Generated by scripts/generate-teavm-widget-tests.py. Do not edit.
package io.instanto.bootstrap.testing.bootstrap3;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertSame;
import static org.junit.Assert.assertTrue;

import com.google.gwt.user.client.ui.IsWidget;
import com.google.gwt.user.client.ui.RootPanel;
import com.google.gwt.user.client.ui.Widget;

final class WidgetFixtureVerifier {
    private WidgetFixtureVerifier() {
    }

    static void verify(String fixtureId, IsWidget fixture) {
        Widget widget = fixture.asWidget();
        assertTrue("fixture must expose a widget", widget != null);
        assertNull("fixture must start without a parent", widget.getParent());
        assertFalse("fixture must start detached", widget.isAttached());
        widget.getElement().setAttribute("data-testid", fixtureId);

        RootPanel root = RootPanel.get();
        root.add(widget);
        try {
            assertSame("root owns mounted fixture", root, widget.getParent());
            assertTrue("mounted fixture is attached", widget.isAttached());
            assertTrue("mounted fixture has a DOM parent", widget.getElement().hasParentElement());
            assertEquals(fixtureId, widget.getElement().getAttribute("data-testid"));
        } finally {
            widget.removeFromParent();
        }

        assertNull("detached fixture has no parent", widget.getParent());
        assertFalse("detached fixture is not attached", widget.isAttached());
        assertFalse("detached fixture has no DOM parent", widget.getElement().hasParentElement());
    }
}
