// Generated by scripts/generate-teavm-widget-tests.py. Do not edit.
package io.instanto.bootstrap.testing.bootstrap5;

import com.google.gwt.user.client.ui.IsWidget;

final class Bootstrap5Fixtures {
    private Bootstrap5Fixtures() {
    }

    static IsWidget abbreviationBasic() {
        return new io.instanto.bootstrap5.client.ui.Abbreviation();
    }

    static IsWidget alertBasic() {
        return new io.instanto.bootstrap5.client.ui.Alert();
    }

    static IsWidget anchorBasic() {
        return new io.instanto.bootstrap5.client.ui.Anchor();
    }

    static IsWidget anchorButtonBasic() {
        return new io.instanto.bootstrap5.client.ui.AnchorButton();
    }

    static IsWidget anchorListItemBasic() {
        return new io.instanto.bootstrap5.client.ui.AnchorListItem();
    }

    static IsWidget badgeBasic() {
        return new io.instanto.bootstrap5.client.ui.Badge();
    }

    static IsWidget blockQuoteBasic() {
        return new io.instanto.bootstrap5.client.ui.BlockQuote();
    }

    static IsWidget booleanRadioGroupBasic() {
        return new io.instanto.bootstrap5.client.ui.BooleanRadioGroup("fixture-group");
    }

    static IsWidget breadcrumbsBasic() {
        return new io.instanto.bootstrap5.client.ui.Breadcrumbs();
    }

    static IsWidget buttonBasic() {
        return new io.instanto.bootstrap5.client.ui.Button();
    }

    static IsWidget buttonGroupBasic() {
        return new io.instanto.bootstrap5.client.ui.ButtonGroup();
    }

    static IsWidget buttonToolBarBasic() {
        return new io.instanto.bootstrap5.client.ui.ButtonToolBar();
    }

    static IsWidget captionBasic() {
        return new io.instanto.bootstrap5.client.ui.Caption();
    }

    static IsWidget cardBasic() {
        return new io.instanto.bootstrap5.client.ui.Card();
    }

    static IsWidget carouselBasic() {
        return new io.instanto.bootstrap5.client.ui.Carousel();
    }

    static IsWidget carouselCaptionBasic() {
        return new io.instanto.bootstrap5.client.ui.CarouselCaption();
    }

    static IsWidget carouselControlBasic() {
        return new io.instanto.bootstrap5.client.ui.CarouselControl();
    }

    static IsWidget carouselIndicatorBasic() {
        return new io.instanto.bootstrap5.client.ui.CarouselIndicator();
    }

    static IsWidget carouselIndicatorsBasic() {
        return new io.instanto.bootstrap5.client.ui.CarouselIndicators();
    }

    static IsWidget carouselInnerBasic() {
        return new io.instanto.bootstrap5.client.ui.CarouselInner();
    }

    static IsWidget carouselSlideBasic() {
        return new io.instanto.bootstrap5.client.ui.CarouselSlide();
    }

    static IsWidget checkBoxBasic() {
        return new io.instanto.bootstrap5.client.ui.CheckBox();
    }

    static IsWidget checkBoxButtonBasic() {
        return new io.instanto.bootstrap5.client.ui.CheckBoxButton();
    }

    static IsWidget codeBasic() {
        return new io.instanto.bootstrap5.client.ui.Code();
    }

    static IsWidget collapseBasic() {
        return new io.instanto.bootstrap5.client.ui.Collapse();
    }

    static IsWidget columnBasic() {
        return new io.instanto.bootstrap5.client.ui.Column();
    }

    static IsWidget containerBasic() {
        return new io.instanto.bootstrap5.client.ui.Container();
    }

    static IsWidget descriptionBasic() {
        return new io.instanto.bootstrap5.client.ui.Description();
    }

    static IsWidget descriptionDataBasic() {
        return new io.instanto.bootstrap5.client.ui.DescriptionData();
    }

    static IsWidget descriptionTitleBasic() {
        return new io.instanto.bootstrap5.client.ui.DescriptionTitle();
    }

    static IsWidget dividerBasic() {
        return new io.instanto.bootstrap5.client.ui.Divider();
    }

    static IsWidget doubleBoxBasic() {
        return new io.instanto.bootstrap5.client.ui.DoubleBox();
    }

    static IsWidget doubleRadioGroupBasic() {
        return new io.instanto.bootstrap5.client.ui.DoubleRadioGroup("fixture-group");
    }

    static IsWidget dropDownBasic() {
        return new io.instanto.bootstrap5.client.ui.DropDown();
    }

    static IsWidget dropDownHeaderBasic() {
        return new io.instanto.bootstrap5.client.ui.DropDownHeader();
    }

    static IsWidget dropDownItemBasic() {
        return new io.instanto.bootstrap5.client.ui.DropDownItem();
    }

    static IsWidget dropDownMenuBasic() {
        return new io.instanto.bootstrap5.client.ui.DropDownMenu();
    }

    static IsWidget fieldSetBasic() {
        return new io.instanto.bootstrap5.client.ui.FieldSet();
    }

    static IsWidget formBasic() {
        return new io.instanto.bootstrap5.client.ui.Form();
    }

    static IsWidget formControlStaticBasic() {
        return new io.instanto.bootstrap5.client.ui.FormControlStatic();
    }

    static IsWidget formGroupBasic() {
        return new io.instanto.bootstrap5.client.ui.FormGroup();
    }

    static IsWidget formLabelBasic() {
        return new io.instanto.bootstrap5.client.ui.FormLabel();
    }

    static IsWidget headingBasic() {
        return new io.instanto.bootstrap5.client.ui.Heading(2);
    }

    static IsWidget helpBlockBasic() {
        return new io.instanto.bootstrap5.client.ui.HelpBlock();
    }

    static IsWidget iconBasic() {
        return new io.instanto.bootstrap5.client.ui.Icon();
    }

    static IsWidget iconStackBasic() {
        return new io.instanto.bootstrap5.client.ui.IconStack();
    }

    static IsWidget imageBasic() {
        return new io.instanto.bootstrap5.client.ui.Image();
    }

    static IsWidget imageAnchorBasic() {
        return new io.instanto.bootstrap5.client.ui.ImageAnchor();
    }

    static IsWidget inlineCheckBoxBasic() {
        return new io.instanto.bootstrap5.client.ui.InlineCheckBox();
    }

    static IsWidget inlineHelpBlockBasic() {
        return new io.instanto.bootstrap5.client.ui.InlineHelpBlock();
    }

    static IsWidget inlineRadioBasic() {
        return new io.instanto.bootstrap5.client.ui.InlineRadio();
    }

    static IsWidget inputBasic() {
        return new io.instanto.bootstrap5.client.ui.Input();
    }

    static IsWidget inputGroupBasic() {
        return new io.instanto.bootstrap5.client.ui.InputGroup();
    }

    static IsWidget inputGroupAddonBasic() {
        return new io.instanto.bootstrap5.client.ui.InputGroupAddon();
    }

    static IsWidget inputGroupButtonBasic() {
        return new io.instanto.bootstrap5.client.ui.InputGroupButton();
    }

    static IsWidget integerBoxBasic() {
        return new io.instanto.bootstrap5.client.ui.IntegerBox();
    }

    static IsWidget integerRadioGroupBasic() {
        return new io.instanto.bootstrap5.client.ui.IntegerRadioGroup("fixture-group");
    }

    static IsWidget jumbotronBasic() {
        return new io.instanto.bootstrap5.client.ui.Jumbotron();
    }

    static IsWidget labelBasic() {
        return new io.instanto.bootstrap5.client.ui.Label();
    }

    static IsWidget leadBasic() {
        return new io.instanto.bootstrap5.client.ui.Lead();
    }

    static IsWidget legendBasic() {
        return new io.instanto.bootstrap5.client.ui.Legend();
    }

    static IsWidget linkedGroupBasic() {
        return new io.instanto.bootstrap5.client.ui.LinkedGroup();
    }

    static IsWidget linkedGroupItemBasic() {
        return new io.instanto.bootstrap5.client.ui.LinkedGroupItem();
    }

    static IsWidget linkedGroupItemTextBasic() {
        return new io.instanto.bootstrap5.client.ui.LinkedGroupItemText();
    }

    static IsWidget listBoxBasic() {
        return new io.instanto.bootstrap5.client.ui.ListBox();
    }

    static IsWidget listDropDownBasic() {
        return new io.instanto.bootstrap5.client.ui.ListDropDown();
    }

    static IsWidget listGroupBasic() {
        return new io.instanto.bootstrap5.client.ui.ListGroup();
    }

    static IsWidget listGroupItemBasic() {
        return new io.instanto.bootstrap5.client.ui.ListGroupItem();
    }

    static IsWidget listItemBasic() {
        return new io.instanto.bootstrap5.client.ui.ListItem();
    }

    static IsWidget longBoxBasic() {
        return new io.instanto.bootstrap5.client.ui.LongBox();
    }

    static IsWidget mediaBodyBasic() {
        return new io.instanto.bootstrap5.client.ui.MediaBody();
    }

    static IsWidget mediaListBasic() {
        return new io.instanto.bootstrap5.client.ui.MediaList();
    }

    static IsWidget modalBasic() {
        return new io.instanto.bootstrap5.client.ui.Modal();
    }

    static IsWidget modalBodyBasic() {
        return new io.instanto.bootstrap5.client.ui.ModalBody();
    }

    static IsWidget modalComponentBasic() {
        return new io.instanto.bootstrap5.client.ui.ModalComponent("div");
    }

    static IsWidget modalFooterBasic() {
        return new io.instanto.bootstrap5.client.ui.ModalFooter();
    }

    static IsWidget modalHeaderBasic() {
        return new io.instanto.bootstrap5.client.ui.ModalHeader();
    }

    static IsWidget navBasic() {
        return new io.instanto.bootstrap5.client.ui.Nav();
    }

    static IsWidget navPillsBasic() {
        return new io.instanto.bootstrap5.client.ui.NavPills();
    }

    static IsWidget navTabsBasic() {
        return new io.instanto.bootstrap5.client.ui.NavTabs();
    }

    static IsWidget navbarBasic() {
        return new io.instanto.bootstrap5.client.ui.Navbar();
    }

    static IsWidget navbarBrandBasic() {
        return new io.instanto.bootstrap5.client.ui.NavbarBrand();
    }

    static IsWidget navbarButtonBasic() {
        return new io.instanto.bootstrap5.client.ui.NavbarButton();
    }

    static IsWidget navbarCollapseBasic() {
        return new io.instanto.bootstrap5.client.ui.NavbarCollapse();
    }

    static IsWidget navbarCollapseButtonBasic() {
        return new io.instanto.bootstrap5.client.ui.NavbarCollapseButton();
    }

    static IsWidget navbarFormBasic() {
        return new io.instanto.bootstrap5.client.ui.NavbarForm();
    }

    static IsWidget navbarHeaderBasic() {
        return new io.instanto.bootstrap5.client.ui.NavbarHeader();
    }

    static IsWidget navbarLinkBasic() {
        return new io.instanto.bootstrap5.client.ui.NavbarLink();
    }

    static IsWidget navbarNavBasic() {
        return new io.instanto.bootstrap5.client.ui.NavbarNav();
    }

    static IsWidget navbarTextBasic() {
        return new io.instanto.bootstrap5.client.ui.NavbarText();
    }

    static IsWidget pageHeaderBasic() {
        return new io.instanto.bootstrap5.client.ui.PageHeader();
    }

    static IsWidget pageItemBasic() {
        return new io.instanto.bootstrap5.client.ui.PageItem();
    }

    static IsWidget pageLinkBasic() {
        return new io.instanto.bootstrap5.client.ui.PageLink();
    }

    static IsWidget pagerBasic() {
        return new io.instanto.bootstrap5.client.ui.Pager();
    }

    static IsWidget paginationBasic() {
        return new io.instanto.bootstrap5.client.ui.Pagination();
    }

    static IsWidget panelBasic() {
        return new io.instanto.bootstrap5.client.ui.Panel();
    }

    static IsWidget panelBodyBasic() {
        return new io.instanto.bootstrap5.client.ui.PanelBody();
    }

    static IsWidget panelCollapseBasic() {
        return new io.instanto.bootstrap5.client.ui.PanelCollapse();
    }

    static IsWidget panelFooterBasic() {
        return new io.instanto.bootstrap5.client.ui.PanelFooter();
    }

    static IsWidget panelGroupBasic() {
        return new io.instanto.bootstrap5.client.ui.PanelGroup();
    }

    static IsWidget panelHeaderBasic() {
        return new io.instanto.bootstrap5.client.ui.PanelHeader();
    }

    static IsWidget paragraphBasic() {
        return new io.instanto.bootstrap5.client.ui.Paragraph();
    }

    static IsWidget popoverBasic() {
        return new io.instanto.bootstrap5.client.ui.Popover(new io.instanto.bootstrap5.client.ui.Button("target"));
    }

    static IsWidget preBasic() {
        return new io.instanto.bootstrap5.client.ui.Pre();
    }

    static IsWidget progressBasic() {
        return new io.instanto.bootstrap5.client.ui.Progress();
    }

    static IsWidget progressBarBasic() {
        return new io.instanto.bootstrap5.client.ui.ProgressBar();
    }

    static IsWidget radioBasic() {
        return new io.instanto.bootstrap5.client.ui.Radio("fixture-group");
    }

    static IsWidget radioButtonBasic() {
        return new io.instanto.bootstrap5.client.ui.RadioButton("fixture-group");
    }

    static IsWidget rangeBasic() {
        return new io.instanto.bootstrap5.client.ui.Range();
    }

    static IsWidget rowBasic() {
        return new io.instanto.bootstrap5.client.ui.Row();
    }

    static IsWidget simpleCheckBoxBasic() {
        return new io.instanto.bootstrap5.client.ui.SimpleCheckBox();
    }

    static IsWidget simpleRadioButtonBasic() {
        return new io.instanto.bootstrap5.client.ui.SimpleRadioButton("fixture-group");
    }

    static IsWidget stringRadioGroupBasic() {
        return new io.instanto.bootstrap5.client.ui.StringRadioGroup("fixture-group");
    }

    static IsWidget submitButtonBasic() {
        return new io.instanto.bootstrap5.client.ui.SubmitButton();
    }

    static IsWidget suggestBoxBasic() {
        return new io.instanto.bootstrap5.client.ui.SuggestBox();
    }

    static IsWidget tabContentBasic() {
        return new io.instanto.bootstrap5.client.ui.TabContent();
    }

    static IsWidget tabListItemBasic() {
        return new io.instanto.bootstrap5.client.ui.TabListItem();
    }

    static IsWidget tabPaneBasic() {
        return new io.instanto.bootstrap5.client.ui.TabPane();
    }

    static IsWidget tabPanelBasic() {
        return new io.instanto.bootstrap5.client.ui.TabPanel();
    }

    static IsWidget textAreaBasic() {
        return new io.instanto.bootstrap5.client.ui.TextArea();
    }

    static IsWidget textBoxBasic() {
        return new io.instanto.bootstrap5.client.ui.TextBox();
    }

    static IsWidget thumbnailLinkBasic() {
        return new io.instanto.bootstrap5.client.ui.ThumbnailLink();
    }

    static IsWidget thumbnailPanelBasic() {
        return new io.instanto.bootstrap5.client.ui.ThumbnailPanel();
    }

    static IsWidget tooltipBasic() {
        return new io.instanto.bootstrap5.client.ui.Tooltip(new io.instanto.bootstrap5.client.ui.Button("target"));
    }

    static IsWidget tooltipHelpBlockBasic() {
        return new io.instanto.bootstrap5.client.ui.TooltipHelpBlock();
    }

    static IsWidget valueListBoxBasic() {
        return new io.instanto.bootstrap5.client.ui.ValueListBox();
    }

    static IsWidget verticalButtonGroupBasic() {
        return new io.instanto.bootstrap5.client.ui.VerticalButtonGroup();
    }

    static IsWidget wellBasic() {
        return new io.instanto.bootstrap5.client.ui.Well();
    }

    static IsWidget markdownMarkdownEditorBasic() {
        return new io.instanto.bootstrap5.extras.markdown.client.ui.MarkdownEditor();
    }

    static IsWidget markdownMarkdownHelpBasic() {
        return new io.instanto.bootstrap5.extras.markdown.client.ui.MarkdownHelp();
    }

    static IsWidget markdownMarkdownPanelBasic() {
        return new io.instanto.bootstrap5.extras.markdown.client.ui.MarkdownPanel();
    }
}
