// Generated by scripts/generate-teavm-widget-tests.py. Do not edit.
package io.instanto.bootstrap.testing.bootstrap5;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.teavm.junit.SkipJVM;
import org.teavm.junit.TeaVMTestRunner;

@RunWith(TeaVMTestRunner.class)
@SkipJVM
public class Bootstrap5WidgetReachabilityTest {
    @Test
    public void abbreviationBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/abbreviation/basic", Bootstrap5Fixtures.abbreviationBasic());
    }

    @Test
    public void alertBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/alert/basic", Bootstrap5Fixtures.alertBasic());
    }

    @Test
    public void anchorBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/anchor/basic", Bootstrap5Fixtures.anchorBasic());
    }

    @Test
    public void anchorButtonBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/anchor-button/basic", Bootstrap5Fixtures.anchorButtonBasic());
    }

    @Test
    public void anchorListItemBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/anchor-list-item/basic", Bootstrap5Fixtures.anchorListItemBasic());
    }

    @Test
    public void badgeBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/badge/basic", Bootstrap5Fixtures.badgeBasic());
    }

    @Test
    public void blockQuoteBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/block-quote/basic", Bootstrap5Fixtures.blockQuoteBasic());
    }

    @Test
    public void booleanRadioGroupBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/boolean-radio-group/basic", Bootstrap5Fixtures.booleanRadioGroupBasic());
    }

    @Test
    public void breadcrumbsBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/breadcrumbs/basic", Bootstrap5Fixtures.breadcrumbsBasic());
    }

    @Test
    public void buttonBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/button/basic", Bootstrap5Fixtures.buttonBasic());
    }

    @Test
    public void buttonGroupBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/button-group/basic", Bootstrap5Fixtures.buttonGroupBasic());
    }

    @Test
    public void buttonToolBarBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/button-tool-bar/basic", Bootstrap5Fixtures.buttonToolBarBasic());
    }

    @Test
    public void captionBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/caption/basic", Bootstrap5Fixtures.captionBasic());
    }

    @Test
    public void cardBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/card/basic", Bootstrap5Fixtures.cardBasic());
    }

    @Test
    public void carouselBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/carousel/basic", Bootstrap5Fixtures.carouselBasic());
    }

    @Test
    public void carouselCaptionBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/carousel-caption/basic", Bootstrap5Fixtures.carouselCaptionBasic());
    }

    @Test
    public void carouselControlBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/carousel-control/basic", Bootstrap5Fixtures.carouselControlBasic());
    }

    @Test
    public void carouselIndicatorBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/carousel-indicator/basic", Bootstrap5Fixtures.carouselIndicatorBasic());
    }

    @Test
    public void carouselIndicatorsBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/carousel-indicators/basic", Bootstrap5Fixtures.carouselIndicatorsBasic());
    }

    @Test
    public void carouselInnerBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/carousel-inner/basic", Bootstrap5Fixtures.carouselInnerBasic());
    }

    @Test
    public void carouselSlideBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/carousel-slide/basic", Bootstrap5Fixtures.carouselSlideBasic());
    }

    @Test
    public void checkBoxBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/check-box/basic", Bootstrap5Fixtures.checkBoxBasic());
    }

    @Test
    public void checkBoxButtonBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/check-box-button/basic", Bootstrap5Fixtures.checkBoxButtonBasic());
    }

    @Test
    public void codeBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/code/basic", Bootstrap5Fixtures.codeBasic());
    }

    @Test
    public void collapseBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/collapse/basic", Bootstrap5Fixtures.collapseBasic());
    }

    @Test
    public void columnBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/column/basic", Bootstrap5Fixtures.columnBasic());
    }

    @Test
    public void containerBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/container/basic", Bootstrap5Fixtures.containerBasic());
    }

    @Test
    public void descriptionBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/description/basic", Bootstrap5Fixtures.descriptionBasic());
    }

    @Test
    public void descriptionDataBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/description-data/basic", Bootstrap5Fixtures.descriptionDataBasic());
    }

    @Test
    public void descriptionTitleBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/description-title/basic", Bootstrap5Fixtures.descriptionTitleBasic());
    }

    @Test
    public void dividerBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/divider/basic", Bootstrap5Fixtures.dividerBasic());
    }

    @Test
    public void doubleBoxBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/double-box/basic", Bootstrap5Fixtures.doubleBoxBasic());
    }

    @Test
    public void doubleRadioGroupBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/double-radio-group/basic", Bootstrap5Fixtures.doubleRadioGroupBasic());
    }

    @Test
    public void dropDownBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/drop-down/basic", Bootstrap5Fixtures.dropDownBasic());
    }

    @Test
    public void dropDownHeaderBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/drop-down-header/basic", Bootstrap5Fixtures.dropDownHeaderBasic());
    }

    @Test
    public void dropDownItemBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/drop-down-item/basic", Bootstrap5Fixtures.dropDownItemBasic());
    }

    @Test
    public void dropDownMenuBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/drop-down-menu/basic", Bootstrap5Fixtures.dropDownMenuBasic());
    }

    @Test
    public void fieldSetBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/field-set/basic", Bootstrap5Fixtures.fieldSetBasic());
    }

    @Test
    public void formBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/form/basic", Bootstrap5Fixtures.formBasic());
    }

    @Test
    public void formControlStaticBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/form-control-static/basic", Bootstrap5Fixtures.formControlStaticBasic());
    }

    @Test
    public void formGroupBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/form-group/basic", Bootstrap5Fixtures.formGroupBasic());
    }

    @Test
    public void formLabelBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/form-label/basic", Bootstrap5Fixtures.formLabelBasic());
    }

    @Test
    public void headingBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/heading/basic", Bootstrap5Fixtures.headingBasic());
    }

    @Test
    public void helpBlockBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/help-block/basic", Bootstrap5Fixtures.helpBlockBasic());
    }

    @Test
    public void iconBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/icon/basic", Bootstrap5Fixtures.iconBasic());
    }

    @Test
    public void iconStackBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/icon-stack/basic", Bootstrap5Fixtures.iconStackBasic());
    }

    @Test
    public void imageBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/image/basic", Bootstrap5Fixtures.imageBasic());
    }

    @Test
    public void imageAnchorBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/image-anchor/basic", Bootstrap5Fixtures.imageAnchorBasic());
    }

    @Test
    public void inlineCheckBoxBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/inline-check-box/basic", Bootstrap5Fixtures.inlineCheckBoxBasic());
    }

    @Test
    public void inlineHelpBlockBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/inline-help-block/basic", Bootstrap5Fixtures.inlineHelpBlockBasic());
    }

    @Test
    public void inlineRadioBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/inline-radio/basic", Bootstrap5Fixtures.inlineRadioBasic());
    }

    @Test
    public void inputBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/input/basic", Bootstrap5Fixtures.inputBasic());
    }

    @Test
    public void inputGroupBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/input-group/basic", Bootstrap5Fixtures.inputGroupBasic());
    }

    @Test
    public void inputGroupAddonBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/input-group-addon/basic", Bootstrap5Fixtures.inputGroupAddonBasic());
    }

    @Test
    public void inputGroupButtonBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/input-group-button/basic", Bootstrap5Fixtures.inputGroupButtonBasic());
    }

    @Test
    public void integerBoxBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/integer-box/basic", Bootstrap5Fixtures.integerBoxBasic());
    }

    @Test
    public void integerRadioGroupBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/integer-radio-group/basic", Bootstrap5Fixtures.integerRadioGroupBasic());
    }

    @Test
    public void jumbotronBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/jumbotron/basic", Bootstrap5Fixtures.jumbotronBasic());
    }

    @Test
    public void labelBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/label/basic", Bootstrap5Fixtures.labelBasic());
    }

    @Test
    public void leadBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/lead/basic", Bootstrap5Fixtures.leadBasic());
    }

    @Test
    public void legendBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/legend/basic", Bootstrap5Fixtures.legendBasic());
    }

    @Test
    public void linkedGroupBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/linked-group/basic", Bootstrap5Fixtures.linkedGroupBasic());
    }

    @Test
    public void linkedGroupItemBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/linked-group-item/basic", Bootstrap5Fixtures.linkedGroupItemBasic());
    }

    @Test
    public void linkedGroupItemTextBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/linked-group-item-text/basic", Bootstrap5Fixtures.linkedGroupItemTextBasic());
    }

    @Test
    public void listBoxBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/list-box/basic", Bootstrap5Fixtures.listBoxBasic());
    }

    @Test
    public void listDropDownBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/list-drop-down/basic", Bootstrap5Fixtures.listDropDownBasic());
    }

    @Test
    public void listGroupBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/list-group/basic", Bootstrap5Fixtures.listGroupBasic());
    }

    @Test
    public void listGroupItemBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/list-group-item/basic", Bootstrap5Fixtures.listGroupItemBasic());
    }

    @Test
    public void listItemBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/list-item/basic", Bootstrap5Fixtures.listItemBasic());
    }

    @Test
    public void longBoxBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/long-box/basic", Bootstrap5Fixtures.longBoxBasic());
    }

    @Test
    public void mediaBodyBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/media-body/basic", Bootstrap5Fixtures.mediaBodyBasic());
    }

    @Test
    public void mediaListBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/media-list/basic", Bootstrap5Fixtures.mediaListBasic());
    }

    @Test
    public void modalBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/modal/basic", Bootstrap5Fixtures.modalBasic());
    }

    @Test
    public void modalBodyBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/modal-body/basic", Bootstrap5Fixtures.modalBodyBasic());
    }

    @Test
    public void modalComponentBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/modal-component/basic", Bootstrap5Fixtures.modalComponentBasic());
    }

    @Test
    public void modalFooterBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/modal-footer/basic", Bootstrap5Fixtures.modalFooterBasic());
    }

    @Test
    public void modalHeaderBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/modal-header/basic", Bootstrap5Fixtures.modalHeaderBasic());
    }

    @Test
    public void navBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/nav/basic", Bootstrap5Fixtures.navBasic());
    }

    @Test
    public void navPillsBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/nav-pills/basic", Bootstrap5Fixtures.navPillsBasic());
    }

    @Test
    public void navTabsBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/nav-tabs/basic", Bootstrap5Fixtures.navTabsBasic());
    }

    @Test
    public void navbarBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/navbar/basic", Bootstrap5Fixtures.navbarBasic());
    }

    @Test
    public void navbarBrandBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/navbar-brand/basic", Bootstrap5Fixtures.navbarBrandBasic());
    }

    @Test
    public void navbarButtonBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/navbar-button/basic", Bootstrap5Fixtures.navbarButtonBasic());
    }

    @Test
    public void navbarCollapseBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/navbar-collapse/basic", Bootstrap5Fixtures.navbarCollapseBasic());
    }

    @Test
    public void navbarCollapseButtonBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/navbar-collapse-button/basic", Bootstrap5Fixtures.navbarCollapseButtonBasic());
    }

    @Test
    public void navbarFormBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/navbar-form/basic", Bootstrap5Fixtures.navbarFormBasic());
    }

    @Test
    public void navbarHeaderBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/navbar-header/basic", Bootstrap5Fixtures.navbarHeaderBasic());
    }

    @Test
    public void navbarLinkBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/navbar-link/basic", Bootstrap5Fixtures.navbarLinkBasic());
    }

    @Test
    public void navbarNavBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/navbar-nav/basic", Bootstrap5Fixtures.navbarNavBasic());
    }

    @Test
    public void navbarTextBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/navbar-text/basic", Bootstrap5Fixtures.navbarTextBasic());
    }

    @Test
    public void pageHeaderBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/page-header/basic", Bootstrap5Fixtures.pageHeaderBasic());
    }

    @Test
    public void pageItemBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/page-item/basic", Bootstrap5Fixtures.pageItemBasic());
    }

    @Test
    public void pageLinkBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/page-link/basic", Bootstrap5Fixtures.pageLinkBasic());
    }

    @Test
    public void pagerBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/pager/basic", Bootstrap5Fixtures.pagerBasic());
    }

    @Test
    public void paginationBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/pagination/basic", Bootstrap5Fixtures.paginationBasic());
    }

    @Test
    public void panelBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/panel/basic", Bootstrap5Fixtures.panelBasic());
    }

    @Test
    public void panelBodyBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/panel-body/basic", Bootstrap5Fixtures.panelBodyBasic());
    }

    @Test
    public void panelCollapseBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/panel-collapse/basic", Bootstrap5Fixtures.panelCollapseBasic());
    }

    @Test
    public void panelFooterBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/panel-footer/basic", Bootstrap5Fixtures.panelFooterBasic());
    }

    @Test
    public void panelGroupBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/panel-group/basic", Bootstrap5Fixtures.panelGroupBasic());
    }

    @Test
    public void panelHeaderBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/panel-header/basic", Bootstrap5Fixtures.panelHeaderBasic());
    }

    @Test
    public void paragraphBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/paragraph/basic", Bootstrap5Fixtures.paragraphBasic());
    }

    @Test
    public void popoverBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/popover/basic", Bootstrap5Fixtures.popoverBasic());
    }

    @Test
    public void preBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/pre/basic", Bootstrap5Fixtures.preBasic());
    }

    @Test
    public void progressBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/progress/basic", Bootstrap5Fixtures.progressBasic());
    }

    @Test
    public void progressBarBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/progress-bar/basic", Bootstrap5Fixtures.progressBarBasic());
    }

    @Test
    public void radioBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/radio/basic", Bootstrap5Fixtures.radioBasic());
    }

    @Test
    public void radioButtonBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/radio-button/basic", Bootstrap5Fixtures.radioButtonBasic());
    }

    @Test
    public void rangeBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/range/basic", Bootstrap5Fixtures.rangeBasic());
    }

    @Test
    public void rowBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/row/basic", Bootstrap5Fixtures.rowBasic());
    }

    @Test
    public void simpleCheckBoxBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/simple-check-box/basic", Bootstrap5Fixtures.simpleCheckBoxBasic());
    }

    @Test
    public void simpleRadioButtonBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/simple-radio-button/basic", Bootstrap5Fixtures.simpleRadioButtonBasic());
    }

    @Test
    public void stringRadioGroupBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/string-radio-group/basic", Bootstrap5Fixtures.stringRadioGroupBasic());
    }

    @Test
    public void submitButtonBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/submit-button/basic", Bootstrap5Fixtures.submitButtonBasic());
    }

    @Test
    public void suggestBoxBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/suggest-box/basic", Bootstrap5Fixtures.suggestBoxBasic());
    }

    @Test
    public void tabContentBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/tab-content/basic", Bootstrap5Fixtures.tabContentBasic());
    }

    @Test
    public void tabListItemBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/tab-list-item/basic", Bootstrap5Fixtures.tabListItemBasic());
    }

    @Test
    public void tabPaneBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/tab-pane/basic", Bootstrap5Fixtures.tabPaneBasic());
    }

    @Test
    public void tabPanelBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/tab-panel/basic", Bootstrap5Fixtures.tabPanelBasic());
    }

    @Test
    public void textAreaBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/text-area/basic", Bootstrap5Fixtures.textAreaBasic());
    }

    @Test
    public void textBoxBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/text-box/basic", Bootstrap5Fixtures.textBoxBasic());
    }

    @Test
    public void thumbnailLinkBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/thumbnail-link/basic", Bootstrap5Fixtures.thumbnailLinkBasic());
    }

    @Test
    public void thumbnailPanelBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/thumbnail-panel/basic", Bootstrap5Fixtures.thumbnailPanelBasic());
    }

    @Test
    public void tooltipBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/tooltip/basic", Bootstrap5Fixtures.tooltipBasic());
    }

    @Test
    public void tooltipHelpBlockBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/tooltip-help-block/basic", Bootstrap5Fixtures.tooltipHelpBlockBasic());
    }

    @Test
    public void valueListBoxBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/value-list-box/basic", Bootstrap5Fixtures.valueListBoxBasic());
    }

    @Test
    public void verticalButtonGroupBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/vertical-button-group/basic", Bootstrap5Fixtures.verticalButtonGroupBasic());
    }

    @Test
    public void wellBasicIsReachable() {
        WidgetFixtureVerifier.verify("core/well/basic", Bootstrap5Fixtures.wellBasic());
    }

    @Test
    public void markdownMarkdownEditorBasicIsReachable() {
        WidgetFixtureVerifier.verify("markdown/markdown-editor/basic", Bootstrap5Fixtures.markdownMarkdownEditorBasic());
    }

    @Test
    public void markdownMarkdownHelpBasicIsReachable() {
        WidgetFixtureVerifier.verify("markdown/markdown-help/basic", Bootstrap5Fixtures.markdownMarkdownHelpBasic());
    }

    @Test
    public void markdownMarkdownPanelBasicIsReachable() {
        WidgetFixtureVerifier.verify("markdown/markdown-panel/basic", Bootstrap5Fixtures.markdownMarkdownPanelBasic());
    }
}
